network.host: 0.0.0.0
node.name: wazuh-indexer
cluster.name: wazuh-cluster
cluster.initial_master_nodes: ["wazuh-indexer"]
plugins.security.disabled: true
path.data: /var/lib/wazuh-indexer
path.logs: /var/log/wazuh-indexer
bootstrap.memory_lock: true
bootstrap.system_call_filter: false
